--- #YAML:1.0
name: Pipeline-Config
version: 0.05
license: perl
distribution_type: module
requires:
  Error: 0.15
  Pipeline: 3.04
  YAML: 0.35
recommends: {}
build_requires:
  Module::Build: 0.20
  Test::More: 0.01
conflicts: {}
provides:
  Pipeline::Config:
    file: lib/Pipeline/Config.pm
    version: 0.05
  Pipeline::Config::Error:
    file: lib/Pipeline/Config/Error.pm
    version: 0.05
  Pipeline::Config::LoadError:
    file: lib/Pipeline/Config/LoadError.pm
    version: 0.05
  Pipeline::Config::UnknownTypeError:
    file: lib/Pipeline/Config/UnknownTypeError.pm
    version: 0.05
  Pipeline::Config::YAML:
    file: lib/Pipeline/Config/YAML.pm
    version: 0.05
  Pipeline::Config::YAML::Search:
    file: lib/Pipeline/Config/YAML.pm
    version: 0.05
generated_by: Module::Build version 0.20
