# Test pipeline configuration file
---
search-packages:
  - not yet functional...
pipeline:
  - Test::Segment
  - a sub pipe:
      - another sub pipe:
          - Test::Segment
      - Test::Segment: { foo: "bar" }
